package com.zenya.aurora.scheduler;

public enum TaskKey {
    TRACK_TPS_TASK,
    TRACK_PLAYER_TASK,
    REFRESH_CHUNK_TASK,

    POINT_PARTICLE,
    LINE_PARTICLE,
    CUBE_PARTICLE,
    RING_PARTICLE,
    CIRCLE_PARTICLE,
    SPHERE_PARTICLE,
    WAVE_PARTICLE
}
